import { useEffect, useState } from "react";

function MapData(){
    const [usersData,setData]=useState([])
    useEffect(()=>{
        setData(user);
    })
    let user=[
        {
            id:1,
            name:"A",
            email:"a@gmail.com",
            age:24,
            phone:574563456
        },
        {
            id:2,
            name:"B",
            email:"a@gmail.com",
            age:26,
            phone:574563456
        },
        {
            id:3,
            name:"C",
            email:"a@gmail.com",
            age:26,
            phone:574563456
        },
        {
            id:4,
            name:"D",
            email:"a@gmail.com",
            age:26,
            phone:574563456
        },
        {
            id:5,
            name:"E",
            email:"a@gmail.com",
            age:26,
            phone:574563456
        },
        {
            id:6,
            name:"F",
            email:"a@gmail.com",
            age:26,
            phone:574563456
        },
        {
            id:7,
            name:"G",
            email:"a@gmail.com",
            age:26,
            phone:574563456
        },
        {
            id:8,
            name:"H",
            email:"a@gmail.com",
            age:26,
            phone:574563456
        },
        {
            id:9,
            name:"J",
            email:"a@gmail.com",
            age:26,
            phone:574563456
        },
    ];
    return(
        <>
        <table border={1} width="100%" style={{ color: "green" }}>
            <thead>
                <tr>
                    <th>id</th>
                    <th>name</th>
                    <th>Email</th>
                    <th>Age</th>
                    <th>Phone</th>
                </tr>
            </thead>
            <tbody>
                {
                    usersData.map((item,index)=>{
                        return(
                            <tr>
                                <td>{item.id}</td>
                                <td>{item.name}</td>
                                <td>{item.email}</td>
                                <td>{item.age}</td>
                                <td>{item.phone}</td>
                            </tr>
                        )
                    })
                }
            </tbody>
        </table>
        </>
    )
}
export default MapData